name: xrpl-amm-clob
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pip
  - matplotlib
  - numpy
  - pandas
  - pyarrow
  - pyspark
  - requests
  - scipy
  - jupyterlab
  - seaborn
  - pytest
  - pytest-cov
  - pytest-xdist
  - pre-commit
  - hypothesis
  - mypy
  - ruff
  - black
  - pip:
      - -e .
      - delta-sharing
